# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            ZPESS
tagline:          'Political Economy Seminar Series in Zurich'
description:      'A Seminar Series on Empirical Political Economy in Zurich'
url:              https://aahrens1.github.io/zpess/
baseurl:          /

author:
  name:           'Achim Ahrens'

paginate:         5
paginate_path: 	  "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# Gems
plugins:
 - jekyll-paginate
 - jekyll-gist
 - redcarpet
